theme: jekyll-theme-minimal
title: Dean Bird - VK4DSB
description: Amateur radio operator, IT security professional, and tinkerer based in Bellmere QLD.
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-feed

future: true

excerpt_separator: <!--more-->

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: default
  - scope:
      path: ""
      type: pages
    values:
      layout: default

feed:
  path: feed.xml
  excerpt_only: true